name: Run unit tests

on:
  push:
    branches:
      - main
      - maven
  schedule:
    - cron: '30 5 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
          cache: maven

      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots -Dsnyk.skip verify

      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging

      - name: Publish container image to Docker Hub
        id: publish
        run: DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }} DOCKERHUB_PASSWORD=${{ secrets.DOCKERHUB_PASSWORD }} mvn --batch-mode clean compile jib:build

#      - name: Publish Test Report
#        if: success() || failure()
#        uses: ScaCap/action-surefire-report@v1.8.0

      - uses: dorny/test-reporter@v1.9.1
        if: success() || failure()
        with:
          name: Junit Test Report
          path: 'target/surefire-reports/*.xml'
          reporter: java-junit
          fail-on-error: true