name: Run unit tests

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 5 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Report
        uses: dorny/test-reporter@v1.9.1
        if: always()
        with:
          name: Junit Tests
          path: '**/build/test-results/test/TEST-*.xml'
          # target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true