#name: Build and publish docker image
#
#on:
#  push:
#    branches:
#      - main
#      - maven
#  release:
#    types: [created]
#
#jobs:
#  publish:
#
#    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#      packages: write
#      id-token: write
#      attestations: write
#
#    steps:
#    - uses: actions/checkout@v4
#    - name: Set up JDK 21
#      uses: actions/setup-java@v4
#      with:
#        java-version: '21'
#        distribution: 'temurin'
#        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
#        settings-path: ${{ github.workspace }} # location for the settings.xml file
#        cache: maven
#
#    - name: Publish container image to Docker Hub
#      id: publish
#      run: DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }} DOCKERHUB_PASSWORD=${{ secrets.DOCKERHUB_PASSWORD }} mvn --batch-mode clean compile jib:build
#
